version: "3.9"
services:
  app:
    volumes:
      - .:/project
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "$DATABASE_NAME"]
      interval: 5s
