version: "3.9"
services:
  app:
    volumes:
      - .:/project
    ports:
      - ${PORT:-3000}:3000

  kibana:
    image: kibana:6.8.3
    ports:
      - ${PORT:-5601}:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch:
