version: "3.9"
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: test
    image: reg.istry.cz/insia/app-test:${TAG:-local}
    environment:
      RAILS_ENV: test
    command: ["sh", "command-test.sh"]
