version: "3.9"
services:
  app:
    volumes:
      - .:/project
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "$DATABASE_NAME"]
      interval: 5s
  elasticsearch:
    image: elasticsearch:6.8.3
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -u elastic:elastic -s -f localhost:9200/_cat/health > /dev/null || exit 1"]
      interval: 5s

  kibana:
    image: kibana:6.8.3
    ports:
      - ${PORT:-5601}:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch:
