version: "3.9"
services:
  app:
    build: .
    image: reg.istry.cz/insia/app:${TAG:-local}
    environment:
      HOST:
      DATABASE_NAME:
      DATABASE_HOST:
      DATABASE_PASSWORD:
  example-file-service:
    image: debian:11-slim
    command:
      - /bin/sh
      - -c
      - |
        while true; do
          date > /data/`date +%s`;
          sleep 10;
        done
    volumes:
      - example-file-service:/data

volumes:
  example-file-service:
