version: "3.9"
services:
  app:
    user: ${APP_USER:-0:0}
    volumes:
      - .:/project
    ports:
      - ${PORT:-3000}:3000

  example-file-service:
    user: ${APP_USER:-0:0}
    volumes:
      - ./data/example-file-service:/data

  kibana:
    image: kibana:6.8.3
    ports:
      - ${PORT:-5601}:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch:
