version: "3.9"
services:
  app:
    volumes:
      - .:/project
    ports:
      - ${PORT:-3000}:3000
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
